name: Fetch Temperature Data

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch data from Apps Script
        run: |
          curl -sL "https://script.googleusercontent.com/macros/echo?user_content_key=AehSKLgIk3iD1PbsjwM7O4hItEOlcZeYnZkrYoNPkF5jk2IzjZ17PH4zIlC7qi4UqbwAASoKQUacOaKQe2dHm0CUGhkMq0Yvc-VtdPiTLl4b1HwE06IL6UH8kM05F62kpQzjDWpj_xokjUV_BeGxNkL-xlPBfVIiU4RGVo5W1G3MX19PXnVD09V8dfiloGm7J2PxFlydSwQ2DTzadZoOcuv8NQgTuCQiFJWG7ExVEuGBX91R7RIJjUeU4hgp0K8B3sDz6bMa5bjUPimlVspSBnrv4ujDhnJ6nINb8LeES80AKccocRb58AI&lib=MjE54VOUTJvBBczSHKNrag3eLxmpFSsFs" -o data.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --cached --quiet || git commit -m "Update data.json [skip ci]"
          git push
        env:
          # Needed for push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
